@echo off
echo [StudyOS Orchestrator] Starting StudyOS (Next.js + Supabase)...

echo [StudyOS Orchestrator] Installing dependencies...
npm install

echo [StudyOS Orchestrator] Starting development server...
npm run dev
